spring.application.name=laborflow-core
server.port=${SERVER_PORT:5581}
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:55432/laborflow_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:admin}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:admin}
spring.datasource.driver-class-name=org.postgresql.Driver
