spring.application.name=laborflow-core
server.port=${SERVER_PORT:5581}
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:55432/laborflow_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:admin}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:admin}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.data.redis.host=${SPRING_DATA_REDIS_HOST:localhost}
spring.data.redis.port=${SPRING_DATA_REDIS_PORT:56379}
spring.data.redis.password=${SPRING_DATA_REDIS_PASSWORD:admin}
spring.data.redis.timeout=${SPRING_DATA_REDIS_TIMEOUT:2s}
spring.cache.type=redis
spring.cache.redis.time-to-live=${SPRING_CACHE_REDIS_TTL:300s}
